import{useMemo,useState}from'react';
type E={id:number;name:string;email:string;phone:string;user_type:string;service:string;message:string;status:string;created_at:string};
const API='http://localhost:5001/api';
const answer=(q:string)=>{let t=q.toLowerCase();if(t.includes('service'))return'DroneTV support covers aerial photography, survey & mapping, inspection and drone solutions.';if(t.includes('course')||t.includes('training')||t.includes('student'))return'Courses include beginner training, practical flying and professional drone applications.';if(t.includes('contact')||t.includes('speak'))return'Please submit the enquiry form with your phone number and our team can contact you.';if(t.includes('register'))return'To register your interest, submit the enquiry form and select a service or course.';if(t.includes('interested'))return'Great! Please share your details in the enquiry form.';if(t.includes('price')||t.includes('cost'))return'Pricing depends on the project. Send an enquiry for a suitable quote.';return'Sorry, I did not understand. Try asking about services, courses, registration or contact.'};

export default function App(){
const[m,setM]=useState([{from:'bot',text:'Hi! I am the Support Assistant. How can I help you?'}]),[q,setQ]=useState(''),[login,setLogin]=useState(false),[admin,setAdmin]=useState(false),[cred,setCred]=useState({email:'',password:''}),[rows,setRows]=useState<E[]>([]),[search,setSearch]=useState(''),[type,setType]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState({name:'',email:'',phone:'',user_type:'',service:'',message:''});
const send=(x=q)=>{if(!x.trim())return;setM(a=>[...a,{from:'user',text:x},{from:'bot',text:answer(x)}]);setQ('')};const reset=()=>setM([{from:'bot',text:'Hi! I am the Support Assistant. How can I help you?'}]);
const submit=async(e:React.FormEvent)=>{e.preventDefault();setNotice('');if(Object.values(form).slice(0,5).some(x=>!x)){setNotice('Please fill all required fields.');return}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)){setNotice('Invalid email.');return}if(!/^[0-9+\\-\s]{7,15}$/.test(form.phone)){setNotice('Invalid phone number.');return}try{let r=await fetch(API+'/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw Error(d.message);setNotice('Enquiry submitted successfully.');setForm({name:'',email:'',phone:'',user_type:'',service:'',message:''})}catch(e:any){setNotice(e.message||'Server error.')}};
const load=async()=>{let r=await fetch(API+'/enquiries',{headers:{'X-Admin-Token':localStorage.adminToken||''}});if(r.ok)setRows(await r.json())};
const doLogin=async()=>{let r=await fetch(API+'/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cred)}),d=await r.json();if(!r.ok)return alert(d.message);localStorage.adminToken=d.token;setAdmin(true);setLogin(false);load()};
const shown=useMemo(()=>rows.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase())&&(!type||x.user_type===type)),[rows,search,type]);
const status=async(id:number,s:string)=>{await fetch(API+'/enquiries/'+id,{method:'PUT',headers:{'Content-Type':'application/json','X-Admin-Token':localStorage.adminToken||''},body:JSON.stringify({status:s})});load()};
const del=async(id:number)=>{if(!confirm('Delete enquiry?'))return;await fetch(API+'/enquiries/'+id,{method:'DELETE',headers:{'X-Admin-Token':localStorage.adminToken||''}});load()};
if(admin)return <div className="admin"><header><b>DroneTV Support — Admin</b><button onClick={()=>{localStorage.removeItem('adminToken');setAdmin(false)}}>Logout</button></header><main><div className="stats"><b>{rows.length}<small>Total</small></b><b>{rows.filter(x=>x.status==='new').length}<small>New</small></b><b>{rows.filter(x=>x.status==='in progress').length}<small>In Progress</small></b><b>{rows.filter(x=>x.status==='closed').length}<small>Closed</small></b></div><section className="panel"><div className="toolbar"><h2>Enquiries</h2><div><input placeholder="Search..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option value="">All Users</option><option>Student</option><option>Customer</option><option>Other</option></select></div></div><table><thead><tr><th>Name</th><th>Contact</th><th>Type</th><th>Service/Course</th><th>Message</th><th>Status</th><th></th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td>{x.name}<small>{new Date(x.created_at).toLocaleString()}</small></td><td>{x.email}<small>{x.phone}</small></td><td>{x.user_type}</td><td>{x.service}</td><td>{x.message||'-'}</td><td><select value={x.status} onChange={e=>status(x.id,e.target.value)}><option>new</option><option>contacted</option><option>in progress</option><option>closed</option></select></td><td><button className="danger" onClick={()=>del(x.id)}>Delete</button></td></tr>)}</tbody></table></section></main></div>;
return <><nav><b>DRONE<span>TV</span></b><div><a href="#services">Services</a><a href="#training">Training</a><a href="#chat">Assistant</a><a href="#enquiry">Enquiry</a><button onClick={()=>setLogin(true)}>Admin</button></div></nav>
<section className="hero"><div><label>DRONE TECHNOLOGY • SUPPORT • LEADS</label><h1>Smart drone solutions,<br/><em>simple support.</em></h1><p>Ask questions, explore services and send your project or training enquiry.</p><a href="#enquiry">Start an Enquiry →</a></div><aside><strong>✦</strong><h2>Support Assistant</h2><p>Quick rule-based answers for common customer and student questions.</p></aside></section>
<section className="section" id="services"><label>SERVICES</label><h2>Drone solutions</h2><div className="cards">{['Aerial Photography','Survey & Mapping','Inspection','Drone Solutions'].map((x,i)=><article><b>0{i+1}</b><h3>{x}</h3><p>Practical drone-enabled solutions planned around your requirements.</p></article>)}</div></section>
<section className="section alt" id="training"><label>COURSES & TRAINING</label><h2>Learn practical drone skills</h2><div className="cards">{['Beginner Drone Training','Practical Flying','Professional Applications'].map((x,i)=><article><b>0{i+1}</b><h3>{x}</h3><p>Training information for students and professionals.</p></article>)}</div></section>
<section className="chat" id="chat"><div><label>SUPPORT ASSISTANT</label><h2>Ask before you enquire.</h2></div><div className="chatbox"><div className="messages">{m.map((x,i)=><p className={x.from} key={i}>{x.text}</p>)}</div><div className="quick">{['What services do you provide?','What courses are available?','How can I contact you?','How can I register?'].map(x=><button onClick={()=>send(x)}>{x}</button>)}</div><div className="input"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()}/><button onClick={()=>send()}>Send</button><button onClick={reset}>Reset</button></div></div></section>
<section className="form" id="enquiry"><div><label>ENQUIRY</label><h2>Tell us what you need.</h2><p>Students and customers can submit their details for follow-up.</p></div><form onSubmit={submit}>{notice&&<div className="notice">{notice}</div>}<div className="grid"><input placeholder="Name *" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Email *" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Phone *" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><select value={form.user_type} onChange={e=>setForm({...form,user_type:e.target.value})}><option value="">User type *</option><option>Student</option><option>Customer</option><option>Other</option></select><select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}><option value="">Service / Course *</option><option>Aerial Photography</option><option>Survey & Mapping</option><option>Inspection</option><option>Drone Training</option><option>Other</option></select></div><textarea placeholder="Message" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><button>Submit Enquiry →</button></form></section><footer>© 2026 DroneTV Support Assistant • Internship Assignment</footer>
{login&&<div className="modal"><div><button className="x" onClick={()=>setLogin(false)}>×</button><h2>Admin Login</h2><input placeholder="Email" value={cred.email} onChange={e=>setCred({...cred,email:e.target.value})}/><input type="password" placeholder="Password" value={cred.password} onChange={e=>setCred({...cred,password:e.target.value})}/><button onClick={doLogin}>Login</button></div></div>}</> }